AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-task to deploy the classification model

  Sample SAM Template for serverless-task

Globals:
  Function:
    Timeout: 10

Resources:
  ClassifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: code/
      Handler: app.lambda_handler
      Runtime: python3.8
      MemorySize: 1024
      Role: arn:aws:iam::667496742526:role/lambda-role
      Environment:
        Variables:
          s3_bucket: kashifs3bucket
          model_name: classification_model.p
      Events:
        Classifier:
          Type: Api
          Properties:
            Path: /classify
            Method: post

Outputs:
  WineClassifierApi:
    Description: API Gateway endpoint URL for Prod stage for WineClassifier function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/classify/